### ISSUE TITLE
Facehugger Crash, but odd behavior?

### ISSUE THREAD

**Issue by SwiftSniffer** [cybercat-mods/gigeresque#207] opened 2023-10-11 22:26 UTC
Upon loading the latest version of everything, a facehugger went to facehug a baby villager, and then crash.
Curiously, upon loading back in my world, I set it to peaceful, and so far, no crash.
I'm not sure if it was a one time crash, but just in case:

[latest.log](https://github.com/cybercat-mods/gigeresque/files/12874997/latest.log)

Edit:
Upon enabling the difficulty back, another facehugger that was on a villager just died on them, and crash the game.
It's not a brand-new world, mind you. But I can try with a new one.
Edit edit:
So it turns out my world was just old and weird? Loading a brand-new world and impregnating a mob doesn't cause a crash.
I hope those details will be useful to you.

**Comment by Ragabagayaga** [comment] 2023-10-12 02:39
The game crashed because the facehugger died, not because the world was old.

**Comment by AzureDoom** [comment] 2023-10-12 14:06
Dupe of #204

**Closed as completed by AzureDoom** 2023-10-12 14:06 UTC
