### ISSUE TITLE
Facehugger death crash

### ISSUE THREAD

**Issue by Ragabagayaga** [cybercat-mods/gigeresque#208] opened 2023-10-12 02:43 UTC
Whenever a facehugger attaches to something and dies the game crashes and presents this:

The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Cannot invoke "mods.cybercat.gigeresque.common.entity.impl.classic.FacehuggerEntity.method_5643(net.minecraft.class_1282, float)" because the return value of "net.minecraft.class_1309.method_31483()" is null

The exit code: -1

**Comment by Ragabagayaga** [comment] 2023-10-12 02:44
The issue is replicable and replicates even after deletion of crash log and making a new profile.

**Comment by AzureDoom** [comment] 2023-10-12 14:06
Dupe of #204

**Closed as completed by AzureDoom** 2023-10-12 14:06 UTC
