### ISSUE TITLE
Projectile Kill Crash

### ISSUE THREAD

**Issue by Ryuco** [cybercat-mods/gigeresque#210] opened 2023-10-17 07:40 UTC
For some reason when i kill face huggers who are actively trying to infect with ranged weaponry it will cause a crash about 1/4 times, it also happened once with another mob from this mod but i wasn't able to recreate that.

I tried using arrows from a bow, and then using projectiles from Simple Animated Guns and both causes this problem although inconsistently. just incase i will put the list of mods i use below, although i dont think so since the crash only happens with these creatures:

[Simple Animated Guns (Fabric) (by ElidhanMC)](https://www.curseforge.com/minecraft/mc-mods/fabric-simple-animated-guns)
[Resourceful Config (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-config)
[Corn Delight [Fabric/Quilt] (by kreloxcz)](https://www.curseforge.com/minecraft/mc-mods/corn-delight-fabric)
[Fabric API (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[Gazebos (RPG Series) (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/gazebos)
[Enderman Overhaul (by joosh_7889)](https://www.curseforge.com/minecraft/mc-mods/enderman-overhaul)
[Expanded Delight [Fabric] (by ianm1647)](https://www.curseforge.com/minecraft/mc-mods/expanded-delight)
[Gigeresque (by cybercat5555)](https://www.curseforge.com/minecraft/mc-mods/gigeresque)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[AzureLib (by AzureDoomC)](https://www.curseforge.com/minecraft/mc-mods/azurelib)
[ChoiceTheorem's Overhauled Village (by ChoiceTheorem)](https://www.curseforge.com/minecraft/mc-mods/choicetheorems-overhauled-village)
[Numismatic Overhaul (by gliscowo)](https://www.curseforge.com/minecraft/mc-mods/numismatic-overhaul)
[YUNG's Better End Island (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-end-island-fabric)
[Trinkets (Fabric) (by EmilyPloszaj)](https://www.curseforge.com/minecraft/mc-mods/trinkets)
[Create Crafts & Additions (by MRHminer)](https://www.curseforge.com/minecraft/mc-mods/createaddition)
[Create: Structures (by FusionSwarly)](https://www.curseforge.com/minecraft/mc-mods/create-structures)
[Small Ships [Fabric & Forge] (by talhanation)](https://www.curseforge.com/minecraft/mc-mods/small-ships)
[Create Big Cannons (by rbasamoyai)](https://www.curseforge.com/minecraft/mc-mods/create-big-cannons)
[Origins (Fabric) (by Apace)](https://www.curseforge.com/minecraft/mc-mods/origins)
[Spell Power Attributes [Fabric] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/spell-power)
[Ad Astra (by AlexNijjar)](https://www.curseforge.com/minecraft/mc-mods/ad-astra)
[End's Delight (by foggyhillside)](https://www.curseforge.com/minecraft/mc-mods/ends-delight)
[Marium's Soulslike Weaponry (by mariumbacchus)](https://www.curseforge.com/minecraft/mc-mods/mariums-soulslike-weaponry)
[SmartBrainLib (Forge/Fabric/Quilt) (by Scimiguy)](https://www.curseforge.com/minecraft/mc-mods/smartbrainlib)
[Resourceful Lib (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[MES - Moog's End Structures (by finndog_123)](https://www.curseforge.com/minecraft/mc-mods/moogs-end-structures)
[Swampier Swamps (Fabric) (by andrew0030)](https://www.curseforge.com/minecraft/mc-mods/swampier-swamps-fabric)
[YUNG's API (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api-fabric)
[Better Combat [Fabric & Forge] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus)
[Farmer's Delight [Fabric] (by NewHoryzon)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric)
[Spell Engine (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/spell-engine)
[Geophilic – Biome Overhauls (by bebebea_loste)](https://www.curseforge.com/minecraft/mc-mods/geophilic)
[Origins: Classes (by Apace)](https://www.curseforge.com/minecraft/mc-mods/origins-classes)
[Nether's Delight (Fabric) (by StevePlayzz_)](https://www.curseforge.com/minecraft/mc-mods/nethers-delight-fabric)
[Jewelry (RPG Series) (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/jewelry)
[Runes [Fabric] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/rune-crafting)
[Dig's DnD Origins (by distantdig)](https://www.curseforge.com/minecraft/mc-mods/digs-dnd-origins)
[Shield Overhaul [Fabric/Forge] (by ElocinDev)](https://www.curseforge.com/minecraft/mc-mods/shield-overhaul)
[Paladins & Priests (RPG Series) (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/paladins-and-priests)
[Combat Roll [Fabric & Forge] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/combat-roll)
[Botarium (by CodexAdrian)](https://www.curseforge.com/minecraft/mc-mods/botarium)
[Pehkui (by Virtuoel)](https://www.curseforge.com/minecraft/mc-mods/pehkui)
[Immersive Aircraft [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-aircraft)
[Projectile Damage Attribute [Fabric & Forge] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/projectile-damage-attribute)
[AzureLib Armor (by AzureDoomC)](https://www.curseforge.com/minecraft/mc-mods/azurelib-armor)
[Wizards (RPG Series) (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/wizards)
[oωo (owo-lib) (by gliscowo)](https://www.curseforge.com/minecraft/mc-mods/owo-lib)
[Create Fabric (by tropheusj)](https://www.curseforge.com/minecraft/mc-mods/create-fabric)

**Comment by Ryuco** [comment] 2023-10-17 07:41
i think it may be because it is struggling to place the acid, since anytime this happens they aren't located on the ground or on a surface.

**Comment by AzureDoom** [comment] 2023-10-17 07:58
Dupe of #204

**Closed as completed by AzureDoom** 2023-10-17 07:58 UTC
