### ISSUE TITLE
Facehugger teleports & goes upside down when facehugging entity behind glass pane

### ISSUE THREAD

**Issue by cuz04** [cybercat-mods/gigeresque#44] opened 2022-05-01 06:06 UTC
Tried to make a facehugger facehug fish by putting some fish between the vindicator and facehugger. To my surprise, the facehugger just teleported to the vindicator and was upside down and not even on the Vindicator's face.
![image](https://user-images.githubusercontent.com/47876902/166133704-594d8152-6d09-4fb6-b826-0e8be21befdf.png)
![image](https://user-images.githubusercontent.com/47876902/166133831-7af15825-1786-4651-94c0-ad8d58f875f1.png)
![image](https://user-images.githubusercontent.com/47876902/166133869-2012eccb-2017-49c1-a9fc-343d514d3f2e.png)

Later tried with a cat and it did the same thing. Teleported, facehugged upside down, and wasn't even properly aligned.
![image](https://user-images.githubusercontent.com/47876902/166134210-f0d329ed-cb0b-4417-8e34-37c7b45fbef8.png)

Also caught the facehugger changing poses while recording another glitch.
![image](https://user-images.githubusercontent.com/47876902/166134362-b641960a-5e22-48d5-b48c-c7aa81cd2141.png)

**Comment by AzureDoom** [comment] 2022-05-01 13:13
Hugging isn't fully configured visually and the tp is a duplicate of #29

**Closed by AzureDoom** 2022-05-01 13:13 UTC
